version: "3"
services:
  selenium:
    build:
      context: /var/opt/test/selenium/
      dockerfile: Dockerfile-selenium
    image: selenium-test-cicd-training
    networks: 
      - my-proxy-net
      
  networks:
    my-proxy-net:
      external:
        name:my_first_network