FROM centos:8

LABEL MAINTAINER="Matthijs Risselada"

RUN yum install -y which

RUN dnf install -y python3

RUN pip3 install selenium

RUN yum install -y wget libXt gtk3 centos-indexhtml hunspell gtk2 liberation-fonts-common hunspell-en-US mozilla-filesystem xcb-util startup-notification liberation-sans-fonts wget bzip2 && yum clean all && rm -rf /var/cache/yum /usr/{games,src,tmp}

RUN wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.26.0-linux64.tar.gz" -O /usr/bin/geckodriver.tgz && tar xvzf /usr/bin/geckodriver.tgz -C /usr/bin && rm -f /usr/bin/geckodriver.tgz

RUN wget -q "https://ftp.mozilla.org/pub/firefox/releases/78.0.1/linux-x86_64/en-US/firefox-63.0.1.tar.bz2" -O /usr/local/ff.bz2 && tar xvjf /usr/local/ff.bz2 -C /usr/local/ && rm -f /usr/local/ff.bz2

RUN mkdir /var/opt/test /var/opt/test/selenium /var/opt/test/selenium/logs

WORKDIR /var/opt/test/selenium

RUN wget -q "https://raw.githubusercontent.com/SYSQA-ExpertiseLeadership/versiebeheer/master/docker-spul/selenium/test-website.py" -O /var/opt/test/selenium/test-website.py

RUN chmod -R 777 /var/opt/test/selenium

RUN cd /var/opt/test/selenium/

RUN ls -alrt

CMD ["python3", "/var/opt/test/selenium/test-website.py"]