version: "3.8"
networks:
  website_my_first_network:
    external: true
      
services:
  selenium:
    build:
      context: /var/opt/test/selenium/
      dockerfile: Dockerfile-selenium
    image: selenium-test-cicd-training
    networks:
      - website_my_first_network
      
