version: "3"
services:
  selenium-test:
    build:
      context: /var/opt/test/selenium/
      dockerfile: Dockerfile-selenium
    image: selenium-test-cicd-training
    volumes: 
      - /var/opt/test/selenium/logs:/var/opt/test/selenium/logs
    
   