FROM centos:8

LABEL MAINTAINER="Matthijs Risselada"

RUN yum install -y which

RUN dnf install -y python3

RUN pip3 install selenium

RUN yum install -y wget libXt gtk3 centos-indexhtml hunspell gtk2 liberation-fonts-common hunspell-en-US mozilla-filesystem xcb-util startup-notification liberation-sans-fonts wget bzip2 && yum clean all && rm -rf /var/cache/yum /usr/{games,src,tmp}

RUN wget -q "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" -O /usr/bin/google-chrome-stable_current_x86_64.rpm

RUN yum install -y /usr/bin/google-chrome-stable_current_x86_64.rpm

RUN wget -q "https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip" -O /usr/local/chromedriver_linux64.zip

RUN yum install -y unzip

RUN unzip /usr/local/chromedriver_linux64.zip -d /usr/local/bin/ 

RUN mkdir /var/opt/test /var/opt/test/selenium /var/opt/test/selenium/logs

WORKDIR /var/opt/test/selenium

RUN wget -q "https://raw.githubusercontent.com/SYSQA-ExpertiseLeadership/versiebeheer/master/docker-spul/selenium/test-website.py" -O /var/opt/test/selenium/test-website.py

RUN chmod -R 777 /var/opt/test/selenium

RUN cd /var/opt/test/selenium/

RUN ls -alrt

CMD ["python3", "/var/opt/test/selenium/test-website.py"]