version: "3.8"
services:
  selenium:
    build:
      context: /var/opt/test/selenium/
      dockerfile: Dockerfile-selenium
    image: selenium-test-cicd-training
    networks:
      - networks:
      - my_first_network
      
networks:
  default:
    external:
      name: my_first_network