version: "3"
services:
  website:
    build:
      context: /var/opt/test/website/
      dockerfile: Dockerfile-nginx
    image: website-image
    ports: 
      - "80:80"
    networks: 
      - proxy
      
  networks:
    proxy:
      driver: bridge