version: "3.8"
services:
  website:
    build:
      context: /var/opt/test/website/
      dockerfile: Dockerfile-nginx
    image: website-image
    ports: 
      - "80:80"
    networks:
      - my_first_network
      
networks:
  default:
    external:
      name: my_first_network