version: "3.8"
networks:
  my_first_network:
    external: false

services:
  website:
    build:
      context: /var/opt/test/website/
      dockerfile: Dockerfile-nginx
    image: website-image
    ports: 
      - "80:80"
    networks:
      - my_first_network